name: TSL
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - joblib=1.4.0
  - numpy=1.23.5
  - pandas=1.5.3
  - pillow=9.3.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.13.2
  - tqdm=4.64.1
  - pytorch=2.1.0=py38_cuda12.1_cudnn8_0
  - pip

  - pip:
    - reformer-pytorch==1.4.4
    - PyWavelets==1.4.1
    - einops==0.8.0
    - patool==1.12
    - sktime==0.16.1
